# Site settings
title: // kuba krymow
email: itskuba@github.io
description: >
  Portfolio for the interwebs.
baseurl: ""
url: "itskuba.github.io"
# github_username:  itskuba

# Build settings
markdown: kramdown
highlighter: rouge

# Collections settings
collections:
  architecture:
    output: true
    permalink: architecture/:title
  3d:
    output: true
    permalink: 3d/:title
