# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: // jakub krymow
email: curvesandsymmetry@github.io
description: >
  Portfolio for the interwebs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "itskuba.github.io" # the base hostname & protocol for your site
# twitter_username: curvesandsymmetry
# github_username:  curvesandsymmetry

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  architecture:
    output: true
    permalink: architecture/:title
  3d:
    output: true
    permalink: 3d/:title
